# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
#COMMON_FLAGS="-O2 -pipe"
#CFLAGS="${COMMON_FLAGS}"
#CXXFLAGS="${COMMON_FLAGS}"
CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=skylake -O2 -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
MAKEOPTS="-j5"
EMERGE_DEFAULT_OPTS="--jobs 4 --load-average 3.6"
APACHE2_MODULES=""
ALSA_CARDS=""
CALLIGRA_FEATURES=""
VIDEO_CARDS="nouveau"
LIBREOFFICE_EXTENSIONS=""
OFFICE_IMPLEMENTATION=""
ACCEPT_KEYWORDS="~amd64"
USE=" x dbus policykit udisks alsa -fortran -gnome -kde -qt4 -qt5 gtk gstreamer imlib jpeg matroska -nls -systemd pdf png -plasma pulseaudio raw -selinux svg elogind -consolekit"
GENTOO_MIRRORS="ftp://mirror.csclub.uwaterloo.ca/gentoo-distfiles/ https://mirror.csclub.uwaterloo.ca/gentoo-distfiles/ http://mirror.csclub.uwaterloo.ca/gentoo-distfiles/"
GRUB_PLATFORMS="efi-64"
