#! /bin/sh
sxhkd &
polybar -c $HOME/.config/polybar/bspwm-polbar.conf main  &
bspc monitor -d web code media edit graphics other
bspc config border_width         3 
bspc config window_gap           5
#bspc config normal_border_color	"$color15" 
bspc config focused_border_color "#FFFFFF"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a google-chrome-stable border=off desktop="web" focus=on follow=on
bspc rule -a TelegramDesktop desktop="web" follow=off
bspc rule -a Leafpad  desktop="code" follow=off
bspc rule -a Geany desktop="code" follow=off
bspc rule -a Pcmanfm desktop="media" state=floating follow=on
bspc rule -a Gimp desktop="graphics" follow=on
bspc rule -a qbittorrent desktop="other" state=floating follow=on
bspc rule -a discord desktop="other" state=pseudo_tiled follow=off

bspc rule -a Xarchiver state=floating
bspc rule -a Leafpad state=floating
bspc rule -a Pcmanfm state=floating focus=on
bspc rule -a URxvt state=floating 
bspc rule -a feh state=floating
