#! /bin/sh
sxhkd &
polybar example &
wal -i $HOME/Downloads/a.jpg
xrdb .Xresources
#compton &
bspc monitor   -d I  II  III  IV  V  VI VII VIII IX X

bspc config border_width         7
bspc config window_gap           5
bspc config normal_border_color "#252628"
bspc config focused_border_color "#c5c8c6"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
